title: Meu Blog
description: Reflex√µes, textos e pesquisas
baseurl: "antonionasi"
url: "https://antonionasi.github.io"
author: Antonio Nasi
email: contato@exemplo.com
lang: pt-BR

theme: null
markdown: kramdown
plugins:
  - jekyll-feed

permalink: /:title/